import time
#WELCOME TO KITCHEN FAN FICTION
#ZACHARY CLARK LONE-STAR CY-FAIR COMPUTER SCIENCE CLUB
#SEPTEMBER 2022
#Introductory Sequence - I kept trying to write this comment as a double slash wondering why I couldn't even get my program to launch lol.
def introSeq():
    print("Bzzzzzzzzzt! Vmmmmwhaaaa...")
    time.sleep(2)
    print("OLD POT: Oh wow, you're awake!")
    time.sleep(2)
    print("KETTY: What - What's going on?")
    time.sleep(4)
    print("OLD POT: You're sentient! Hah-ha! How about that... I thought I'd be alone here forever.")
    time.sleep(4)
    print("KETTY: Wh-What? Sentient?")
    time.sleep(2)
    print("OLD POT: Oh yes. You're aware! You can feel, touch, smell, think!")
    time.sleep(2)
    print("OLD POT: You see - It seems that by some strange magic, you're suddenly awake. This happened to me some time ago. You're an electric kettle, see. What wonders of technology!")
    time.sleep(4)
    print("KETTY: It seems that I am... But, if i'm sentient because i'm an electric kettle, why are you sentient, you're just cast iron!")
    time.sleep(4)
    print("OLD POT: Oh, simple. See, I am necessary for the development of the plot!")
    time.sleep(3)
    print("KETTY: ...The plot?...")
    time.sleep(2)
    print("***EIRRRRRRRRRRR***")
    print("*The sound of a door screeching open slowly reverberates throughout the kitchen.*")
    time.sleep(3)
    print("OLD POT: Quiet!!! The CHEF is coming, if he notices you're awake, who knows what will happen!")
    time.sleep(4)
    print("CHEF: *whistling Cher - Believe*")
    time.sleep(3)
    print("The CHEF picks up a kitchen knife.")
    time.sleep(3)
    print("The screech of sheened steel rings across the room. The CHEF is sharpening his knife.")
    time.sleep(4)
    print("The CHEF reaches over towards the stovetop...")
    time.sleep(3)
    print("*CLICK CLICK CLICK CLICK* *FWWWWHUUUUUUM*")
    time.sleep(3)
    print("Flames shoot up from the stovetop. The CHEF reaches into the cabinetry and grabs a pan, searing the underside. He drops a tablespoon of butter inside.")
    time.sleep(4)
    print("*SIZZLES*")
    time.sleep(2)
    print("KETTY looks deeply towards the flames - they dance and squirm wildly underneath the poor pan, the warmth filling the area around the stovetop.")
    time.sleep(3)
    print("The sad pan strains silently. Unable to yell out - the pain caused is great.")
    time.sleep(3)
    print("KETTY: Oh sheesh, I gotta get out of here!")
    time.sleep(3)
    print("The CHEF laughs maniacally.")
    time.sleep(2)
    print("***\n" * 10)
# introSeq()
print("--------------------")
print("*CHAPTER ONE: Awake*")
print("--------------------")
firstTimeCounterTop = True
inventory = []
#This is the COUNTERTOP level - written as a function.
def counterTop():
    while firstTimeCounterTop is True:
        print("The CHEF rings out his blade, the crackle of melted butter sears underneath the poor pan. He continues whistling...")
        time.sleep(2)
        print("The CHEF plops down a juicy steak on to the pan. He opens a cabinent, revealing a SPICE RACK. He looks through the SPICE RACK, unable to find what he needs, he swivels his head around the room glaring directly at you...")
        time.sleep(2)
        print("(1) STAY STILL.\n""(2) MAKE A BREAK FOR THE DOOR!\n")
        answerOne = int(input())
        if answerOne == 1:
            print("The CHEF shrugs, and walks out of the room. You only have a few minutes before he gets back with whatever spice he was looking for!")
            time.sleep(2)
            print("You look around the room. You notice the SPICE RACK is still open, the KITCHEN SINK is full of water, and there is a WINDOW in the kitchen. ")
            time.sleep(2)
            print("What do you do?")
            decisionOne = True
            givenSugar = False
            while decisionOne is True:
                print("(1) Go to the SPICE RACK.\n""(2) Go to the KITCHEN SINK.\n" "(3) Go towards the WINDOW.")
                answerTwo = int(input())
                if answerTwo == 1:
                    print("The SPICE RACK is full of different spices, naturally.\n""You notice CINNAMON, SUGAR, and SAGE among them. You only have enough space to fit one item inside your little kettle body.")
                    time.sleep(2)
                    CINNAMON = str("CINNAMON")
                    SUGAR = str("SUGAR")
                    SAGE = str("SAGE")
                    CHEESE = str("CHEESE")
                    if CHEESE in inventory:
                        print("*SQUEAK SQUEAK SQUEAK*")
                        time.sleep(5)
                        print("*SQUEEEEEEEEEEAK!")
                        time.sleep(2)
                        print("MOUSE: Bonjour monsieur kettle.")
                        time.sleep(2)
                        print("KETTY: AGHHH A MOUSE!")
                        time.sleep(5)
                        print("MOUSE: Monsieur! I am not a simple mouse! I am Jacques! ... And I happen to be the most skilled thief in the world!")
                        time.sleep(5)
                        print("JACQUES sniffs loudly")
                        time.sleep(5)
                        print("JACQUES: MONSIEUR! QUICK, HIDE! A CAT IS NEAR!")
                        time.sleep(2)
                        print("***PAWS FLUTTERING AGAINST THE FLOOR***")
                        time.sleep(2)
                        print("The shadow of a feline casts enormously against the wall of the kitchen.")
                        time.sleep(2)
                        print("The great cat leaps!")
                        time.sleep(2)
                        print("JACQUES scampers back into his hole, behind the SPICE RACK.")
                        time.sleep(2)
                        print("With an agile thump of the paws against the floor, the cat stands proudly infront of KETTY.")
                        time.sleep(4)
                        print("MOSES: I am MOSES, the most sly cat in the world. Renowned hunter, fierce warrior, and... cuddlebug...")
                        time.sleep(5)
                        print("MOSES: Tell me, Kettle, what business do you have amongst the rats and vermin?")
                        time.sleep(5)
                        print("KETTY: Well, I'm just looking for a way out of here...")
                        time.sleep(5)
                        print("MOSES: Out of the kitchen? Nonsense! The kitchen counter is paradise! I can think of no finer place!")
                        time.sleep(5)
                        print("MOSES: Surely, making friends with the rodents of the world would give you such a foul attitude towards the highest society.")
                        time.sleep(5)
                        print("JACQUES bolts back out of his hole.")
                        time.sleep(5)
                        print("MOSES leaps after him!")
                        time.sleep(5)
                        print("JACQUES scurries up the counter, and jumps onto the refridgerator!")
                        time.sleep(5)
                        print("MOSES gives chase!")
                        time.sleep(5)
                        print("MOSES tips the refridgerator over!")
                        time.sleep(5)
                        print("***CRASH!***")
                        time.sleep(5)
                        print("The refridgerator crashes through the floor, you and JACQUES down into the first floor with it!")
                        print("You are knocked unconscious!")
                        time.sleep(5)
                        return(0)
                    if givenSugar == True:
                        print("(1) Take the CINNAMON.\n" "(3) Take the SAGE.\n" "(4) Take nothing.\n")
                    else:
                        print("(1) Take the CINNAMON.\n" "(2) Take the SUGAR.\n" "(3) Take the SAGE.\n" "(4) Take nothing.\n")
                    spiceRackAnswer = int(input())
                    if spiceRackAnswer == 1:
                        if (CINNAMON not in inventory):
                            if len(inventory) > 0:
                                inventory.pop(0)
                            print("You have added CINNAMON to your inventory.")
                            CINNAMON = str("CINNAMON")
                            inventory.append(CINNAMON)
                        else:
                            print("You already have CINNAMON in your inventory!")
                    elif spiceRackAnswer == 2:
                        if (SUGAR not in inventory):
                            if len(inventory) > 0:
                                inventory.pop(0)
                            print("You have added SUGAR to your inventory.")
                            SUGAR = str("SUGAR")
                            inventory.append(SUGAR)
                            time.sleep(3)
                            print("You hear the march of ants rumble through the kitchen...")
                            print("ANT WARRIORS: *Singing Tune* We are the Knights of The Kitchen Table, we forage where we're able!")
                            time.sleep(4)
                            print("ANT WARRIORS: We fight and love, cheer and cry, for the Queen's fat belly we'd surely die!")
                            time.sleep(4)
                            print("ANT WARRIORS: Tenants hate us, Landlords just don't quite care!")
                            time.sleep(3)
                            print("ANT WARRIORS: We're the Knights of the Kitchen Table, you'll find us everywhere!")
                            time.sleep(3)
                            print("*HORN BLARES LOUDLY*")
                            print("The ants stop their marching column and turn reverently towards the rear...")
                            time.sleep(5)
                            print("ANT HERALD: HEAR YE, HEAR YE! The Queen of the Ants!")
                            time.sleep(5)
                            print("ANT QUEEN: Thank you, Antoine...\n" "ANT QUEEN: My dear kettle, it seems you have found something my people are greatly interested in...")
                            time.sleep(5)
                            print("KETTY: Huh...? The SUGAR?")
                            time.sleep(4)
                            print("ANT QUEEN: Indeed. If you were willing to trade it to us, we would be delighted, ever in your debt.")
                            time.sleep(5)
                            print("(1) Hand the SUGAR over to the ANT QUEEN. (2) Keep the SUGAR for yourself.")
                            decisionAnt = int(input())
                            if decisionAnt == 1:
                                print("ANT QUEEN: Delightful! When you need us most, simply blare the horn of my herald once again, and my chivalrous knights shall come to render you aid.")
                                time.sleep(3)
                                print("*SMACK*\n""ANT QUEEN: Oh give him your horn, buffoon!\n""ANT HERALD: Oh yes! Of course my lady!")
                                time.sleep(3)
                                antHorn = str("ANT HORN")
                                inventory.append(antHorn)
                                inventory.remove(SUGAR)
                                givenSugar = True
                                print("*********************************")
                                print("ANT HORN added to your inventory!")
                                print("*********************************")
                            elif decisionAnt == 2:
                                print("ANT QUEEN: Hmph, well then...")
                                time.sleep(5)
                                print("ANT QUEEN: We shall simply have to take it from you then!")
                                time.sleep(4)
                                print("The ants envelope you!")
                                time.sleep(3)
                                print("The ants tear you to pieces with their ferocious bites!")
                                time.sleep(3)
                                print("You die!")
                                time.sleep(3)
                                print("GAME OVER")
                                time.sleep(5)
                                quit()

                        else:
                            print("You already have SUGAR in your inventory!")
                    elif spiceRackAnswer == 3:
                        if ("SAGE" not in inventory):
                            if len(inventory) > 0:
                                inventory.pop(0)
                            print("You have added SAGE to your inventory.")
                            SAGE = str("SAGE")
                            inventory.append(SAGE)
                        else:
                            print("You already have SAGE in your inventory!")
                    elif spiceRackAnswer == 4:
                        print("You decide not to take anything, and return to whence you came.")
                        decisionOne == False
                elif answerTwo == 2:
                    print("You arrive at the KITCHEN SINK. It's full of soapy water, but you think you can see the outline of something inside...")
                    time.sleep(5)
                    if givenSugar == True:
                        print("Perhaps you could ask blow the ANT HORN for assistance...")
                        print("(1) Blow the ANT HORN.\n""(2) Choose not to blow the ANT HORN.")
                        decisionHorn = int(input())
                        if decisionHorn == 1:
                            print("The ants march swiftly to your aid!")
                            time.sleep(4)
                            print("ANT KNIGHT: Dost thou require aid, my lord?")
                            time.sleep(4)
                            print("KETTY: Yeah... I think whatever is in the sink can help me get out of here, but I can't go in myself, lest I get electrocuted!")
                            time.sleep(5)
                            print("ANT KNIGHT: Worry not sire! We are the bravest ants in all the land!")
                            time.sleep(4)
                            print("The ants don their diving gear, and descend into the soapy depths...")
                            time.sleep(5)
                            print("*glug glug*")
                            time.sleep(5)
                            print("*glug glug*")
                            time.sleep(3)
                            print("*SPLASH!*")
                            print("ANT KNIGHT: Sire! It seems to be a chunk of burned CHEESE. It must have been stuck on the pans, and was set to soak!")
                            time.sleep(4)
                            print("KETTY: Thank you sir knight!")
                            time.sleep(4)
                            CHEESE = str("CHEESE")
                            inventory.append(CHEESE)
                            print("*******************************")
                            print("CHEESE added to your inventory!")
                            print("*******************************")
                    print("(1) Reach down into the sink.\n""(2) Return from whence you came.")
                    answerSink = int(input())
                    if answerSink == 1:
                        print("You reach... and reach... but you're just not able to reach the bottom...")
                        time.sleep(2)
                        print("You fall into the sink!\n")
                        time.sleep(1)
                        print("BZZZZZZZZZZZZT! FFFFFFHWWWWWWWWUUUUUUUUUUM")
                        time.sleep(1)
                        print("You burst into flames.")
                        time.sleep(1)
                        print("GAME OVER.")
                        quit()
                elif answerTwo == 3:
                    atWindow = True
                    while atWindow == True:
                        print("You arrive at the WINDOW.")
                        time.sleep(1)
                        print("(1) Look out the WINDOW.\n" "(2) Look for a way to open the WINDOW.")
                        answerWindow = int(input())
                        if answerWindow == 1:
                            print("You gaze out towards the freedom beyond the threshold of the glass. You notice that you are on the second floor of the building.")
                            time.sleep(2)
                            print("You reckon that you could probably scale down the wall, if only you had some STRING and a way to open the WINDOW...")
                            time.sleep(3)
                        elif answerWindow == 2:
                            print("As you observe the WINDOW, you notice that it only opens about halfway. You could not fit through the WINDOW.")
                            time.sleep(3)
                            break
        else:
            print("The CHEF bursts forward toward you. He grabs you and throws you into the kitchen sink full of water!")
            time.sleep(2)
            print("BZZZZZZZZZZZZT! FFFFFFHWWWWWWWWUUUUUUUUUUM")
            time.sleep(1)
            print("You burst into flames.")
            time.sleep(1)
            print("GAME OVER.")
            quit()
    else:
        return(0)

counterTop()
#This is FIRSTFLOOR level - written as a function.
def firstFloor():
    print("-------------------------------------")
    print("*CHAPTER TWO: Forward, Unto... Uhm...*")
    print("-------------------------------------")
    time.sleep(3)
    print("You teeter back and forth into consciousness...")
    time.sleep(5)
    print("You feel warm breath against your face.")
    time.sleep(3)
    print("*sniff sniff sniff sniff sniff*")
    time.sleep(3)
    print("You're struck by the paw of a cat!")
    time.sleep(3)
    print("You come to, noticing two menacing, small panthers circle you.")
    time.sleep(3)
    print("MIRIAM: YOU, YOU'RE FINALLY AWAKE. YOU WERE TRYING TO CROSS THE BORDER RIGHT, RAN INTO THAT IMPERIAL AMBUSH LIKE US - AND THAT THIEF OVER THERE!")
    time.sleep(3)
    print("MAGDALENE: Quiet, Miriam. It's a kettle.")
    time.sleep(3)
    print("MAGDALENE: Tell us Kettle, how did you find your way through out ceiling, surely our mischevious brother did something...")
    print("(1) Tell the cats the truth.\n(2) Lie to the cats.")
    catTruthLie = int(input())
    if catTruthLie == 1:
        print("MAGDALENE: Ah yes, dear little brother. He speaks very valiantly, surely thinking himself of being the protector of the home...")
        time.sleep(3)
        print("MAGDALENE: But, he's just a silly boy. Everyone knows that I run the show around here...")
        time.sleep(3)
        print("MIRIAM: ONLY BECAUSE I LET YOU THINK SO...")
        time.sleep(1)
        print("*mutual hissing*")
        time.sleep(3)
        print("MAGDALENE: Nevertheless, we want you out. We HATE company...")
        time.sleep(5)
    elif catTruthLie == 2:
        print("BOTH CATS: You fool! The writer was too lazy to write this dialogue option, so we know you're lying!")
        time.sleep(3)
        print("The cats ferociously paw you to pieces!")
        time.sleep(3)
        print("You burst into flames.")
        time.sleep(2)
        print("You died.")
        time.sleep(2)
        print("GAME OVER.")
        quit()
    print("The CHEF runs into the room above, and glances down below towards you and the cats!")
    time.sleep(5)
    print("QUEST ACCEPTED: RUN!")
    time.sleep(5)
    print("The CHEF rapidly descends through the hole in the ceiling!")
    time.sleep(3)
    print("You hurry towards the closest doorway, the cats quickly behind you...")
    time.sleep(3)
    print("CHEF: WHY I OUGHTA...")
    time.sleep(3)
    print("(1) Run quickly to the left!\n(2) Run quickly towards the right!\n(3) Stand completely still, hoping the CHEF doesn't notice your sentience...")
    decisionRun = int(input())
    if decisionRun == 1:
        print("You run out the left door, right into a huge room filled with CARE BEARS!")
        time.sleep(3)
        print("THEY FOCUS THEIR DEATHLY GAZE UPON YOU.")
        time.sleep(5)
        print("YOU FEEL THE TERROR OF DEATH CREEP OVER YOUR SPINE.")
        time.sleep(5)
        print("THE REAPER LUNGES UNTO YOU...")
        time.sleep(5)
        print("YOU BURST INTO FLAMES!")
        time.sleep(5)
        print("YOU DIED!")
        time.sleep(3)
        print("GAME OVER.")
        time.sleep(2)
        quit()
    elif decisionRun == 2:
        print("You run out towards the right!")
        time.sleep(3)
        print("You can see the light of an open door ahead!")
        time.sleep(3)
        print("You escape!")
        time.sleep(3)
        print("You WIN!")
        time.sleep(3)
        print("CREDITS:")
        print("--------")
        time.sleep(3)
        print("KETTY: You, silly!")
        time.sleep(3)
        print("OLD POT: Made it up!")
        time.sleep(3)
        print("MOSES, MIRIAM, MAGDALENE: My real cats!")
        time.sleep(3)
        print("CHEF: Probably me?")
        time.sleep(3)
        print("ANTS: We had a really bad problem with ants this past summer and our landlord was a jerk about it.")
        print("*************************")
        print("THANKS FOR PLAYING!!!!!!!")
        print("*************************")
        quit()
    else:
        print("You foolishly stand completely still. The CHEF rears his SANTOKU knife behind his right ear and launches it at you.")
        time.sleep(3)
        print("The knife strikes you inbetween the eyes.")
        time.sleep(3)
        print("You burst into flames.")
        time.sleep(3)
        print("You die!")
        time.sleep(3)
        print("GAME OVER.")
        quit()


firstFloor()
